name: Deploy Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalacja Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Weryfikacja instalacji
        run: ansible --version

      - name: Uruchomienie playbooka
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
        
            
